[package]
name = "vcp-media-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive = "1.0"
serde = { version = "1.0.101", optional = true, features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3.18"
tracing-error = "0.2.0"
log = "0.4.21"
tracing-appender = "0.2.3"
chrono = "0.4.37"
